---
## TODO
- name: Install Network Utils
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - bridge-utils
  ignore_errors: yes

- name: Install Ganeti and tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ganeti
    - ganeti-instance-debootstrap
    - snf-image
  ignore_errors: yes
