---
- name: Install Network Utils
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - bridge-utils

- name: Install Hypervisor
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - qemu-kvm
    - libvirt
    - python-virtinst # CentOS 7.8.2003 can't find this, not installed on my existing cluster
    - virt-install
    - bridge-utils
  ignore_errors: yes

- name: Install Ganeti and tools
  ansible.builtin.yum:
    enablerepo: epel,integ-ganeti
    name: "{{ item }}"
    state: present
  loop:
    - ganeti
    - ganeti-instance-debootstrap
    - snf-image
  ignore_errors: yes

- name: Install DRBD
  ansible.builtin.yum:
    enablerepo: elrepo
    name: "{{ item }}"
    state: present
  loop:
    - drbd84-utils
    - kmod-drbd84
  ignore_errors: yes
