---
- hosts: all
  tasks:
    - name: Add NodeJS Key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      when: ansible_distribution == 'Debian'
      become: True

    - name: Added MongoDB Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.4.asc
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: True

    - name: Add NodeJS Debian Repo
      apt_repository:
        filename: nodesource
        repo: "deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
        state: present
      when: ansible_distribution == 'Debian'
      become: True

    - name: Added MongoDB Repo - Debian
      apt_repository:
        repo: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/4.4 main"
        state: present
        filename: mongodb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      become: True

    - name: Install base requirements
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - vim
        - wget
        - python3
        - nodejs
        - mongodb-org
      become: True

    - name: Create GenieACS user
      user:
        name: genieacs
        create_home: no
        system: yes
        state: present
      become: True

    - name: Install "genieacs" node.js package on version 1.2.2.
      npm:
        name: genieacs
        version: '1.2.2'
        global: yes
        unsafe_perm: yes
      become: True

    - name: Create requires folders for GenieACS
      file:
        path: /opt/genieacs
        owner: root
        group: root
        state: directory
      become: True

    - name: Create requires folders for GenieACS
      file:
        path: /opt/genieacs/ext
        owner: genieacs
        group: genieacs
        state: directory
      become: True

    - name: Create log foler for GenieACS
      file:
        path: /var/log/genieacs
        owner: genieacs
        group: genieacs
        state: directory
      become: True
