---
- name: Install base requirements
  ansible.builtin.package:
    name: gnupg2 #required to add keys!
    state: present

- name: Install base requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - vim
    - wget
    - python3