---
- hosts: all
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
      become: True
      when: ansible_distribution == "Ubuntu"

    # Due to the box being used, there is an old kernel present
    - name: apt remove old kernel version
      ansible.builtin.apt:
        name:
          - linux-cloud-tools-5.4.0-42-generic
          - linux-image-5.4.0-42-generic
          - linux-tools-5.4.0-42-generic
        state: absent
      become: True
      when: ansible_distribution == "Ubuntu"

    # Remove init for old kernel present
    - name: remove unused initrd.img files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /boot/initrd.img-5.4.0-42-generic.img
        - /boot/initrd.img-5.4.0-169-generic.img
      become: True
      when: ansible_distribution == "Ubuntu"

    - name: apt autoremove
      ansible.builtin.apt:
        autoremove: yes
        purge: true
      become: True
      when: ansible_distribution == "Ubuntu"

    - name: Update base packages
      ansible.builtin.package:
        name: "*"
        state: latest
      become: True

    - name: Install base requirements
      ansible.builtin.package:
        name:
          - git
          - make
          - libxml2-dev
          - perl
          - libcap-dev
          - libtool
          - libnghttp2-dev
          - libuv1-dev
          - libssl-dev
          - liburcu-dev
          - libjemalloc-dev
          - zlib1g-dev
          - libmaxminddb-dev
          - libidn2-dev
          - libedit-dev
          - python3-pytest
        state: present
      become: True

    - name: Get ISC BIND9 Source
      ansible.builtin.git:
        repo: https://gitlab.isc.org/isc-projects/bind9.git
        dest: ~/bind9
        depth: 1
        force: true
        single_branch: true
        version: stable

    - name: Autoreconf files for ISC BIND9
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: autoreconf -if

    - name: configure make files for ISC BIND9
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: ./configure --prefix="" --sysconfdir=/etc/bind --localstatedir=/var --disable-static --with-openssl --with-libxml2

    - name: ISC BIND9 - make
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: make

    - name: ISC BIND9 - make install
      ansible.builtin.shell:
        chdir: /home/vagrant/bind9
        cmd: make install
      become: True
