---
- hosts: all
  tasks:
    - name: apt update
      ansible.builtin.apt:
        update_cache: yes
      become: True
      when: ansible_distribution == "Ubuntu"

    # Due to the box being used, there is an old kernel present
    - name: apt remove old kernel version
      ansible.builtin.apt:
        name:
          - linux-cloud-tools-5.4.0-42-generic
          - linux-image-5.4.0-42-generic
          - linux-tools-5.4.0-42-generic
        state: absent
      become: True
      when: ansible_distribution == "Ubuntu"

    # Remove init for old kernel present
    - name: remove unused initrd.img files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /boot/initrd.img-5.4.0-42-generic.img
        - /boot/initrd.img-5.4.0-169-generic.img
      become: True
      when: ansible_distribution == "Ubuntu"

    - name: apt autoremove
      ansible.builtin.apt:
        autoremove: yes
        purge: true
      become: True
      when: ansible_distribution == "Ubuntu"

    - name: Update base packages
      ansible.builtin.package:
        name: "*"
        state: latest
      become: True

    - name: Install base requirements
      ansible.builtin.package:
        name:
          - git
          - libcap-dev
          - libedit-dev
          - libfstrm0
          - libfstrm-dev
          - libidn2-dev
          - libjemalloc2
          - libjemalloc-dev
          - libjson-c-dev
          - libkrb5-dev
          - liblmdb-dev
          - libmaxminddb-dev
          - libnghttp2-dev
          - libprotobuf-c1
          - libprotobuf-c-dev
          - libssl-dev
          - libtool
          - liburcu-dev
          - libuv1-dev
          - libxml2-dev
          - make
          - perl
          - protobuf-c-compiler
          - python3-pytest
          - zlib1g-dev
        state: present
      become: True

    - name: Get ISC BIND9 Source
      ansible.builtin.git:
        repo: https://gitlab.isc.org/isc-projects/bind9.git
        dest: ~/bind9
        depth: 1
        force: true
        single_branch: true
        version: stable

    - name: Autoreconf files for ISC BIND9
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: autoreconf -if

    - name: configure make files for ISC BIND9
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: "./configure {{ make_cfg_opts | join(' ') }}"
      vars:
        make_cfg_opts:
          - --build=x86_64-linux-gnu
          - --prefix=/usr
          - --includedir=\$\{prefix\}/include
          - --mandir=\$\{prefix\}/share/man
          - --infodir=\$\{prefix\}/share/info
          - --sysconfdir=/etc
          - --localstatedir=/var
          - --disable-silent-rules
          - --libdir=\$\{prefix\}/lib/x86_64-linux-gnu
          - --libexecdir=\$\{prefix\}/lib/x86_64-linux-gnu
          - --disable-maintainer-mode
          - --disable-dependency-tracking
          - --libdir=/usr/lib/x86_64-linux-gnu
          - --sysconfdir=/etc/bind
          - --with-python=python3
          - --localstatedir=/
          - --enable-threads
          - --enable-largefile
          - --with-libtool
          - --enable-shared
          - --disable-static
          - --with-gost=no
          - --with-openssl=/usr
          - --with-gssapi=yes
          - --with-libidn2
          - --with-json-c
          - --with-lmdb=/usr
          - --with-gnu-ld
          - --with-maxminddb
          - --with-atf=no
          - --enable-ipv6
          - --enable-rrl
          - --enable-filter-aaaa
          - --disable-native-pkcs11
          - --enable-dnstap
          - build_alias=x86_64-linux-gnu
          - CFLAGS="-g -O2 -fdebug-prefix-map=/build/bind9-fzLItU/bind9-9.20.9=. -fstack-protector-strong -Wformat -Werror=format-security -fno-strict-aliasing -fno-delete-null-pointer-checks -DNO_VERSION_DATE -DDIG_SIGCHASE"
          - LDFLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now"
          - CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"

    - name: ISC BIND9 - make
      ansible.builtin.shell:
        chdir: ~/bind9
        cmd: make

    - name: ISC BIND9 - make install
      ansible.builtin.shell:
        chdir: /home/vagrant/bind9
        cmd: make install
      become: True

    - name: remove build packages
      ansible.builtin.package:
        name:
          - libcap-dev
          - libedit-dev
          - libfstrm-dev
          - libidn2-dev
          - libjemalloc-dev
          - libjson-c-dev
          - libkrb5-dev
          - liblmdb-dev
          - libmaxminddb-dev
          - libnghttp2-dev
          - libprotobuf-c-dev
          - libssl-dev
          - libtool
          - liburcu-dev
          - libuv1-dev
          - libxml2-dev
          - make
          - perl
          - protobuf-c-compiler
          - python3-pytest
          - zlib1g-dev
        state: absent
      become: True

    - name: Post build - apt autoremove
      ansible.builtin.apt:
        autoremove: yes
        purge: true
      become: True
      when: ansible_distribution == "Ubuntu"
