---
- hosts: all
  tasks:
    - name: Install base requirements
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - vim
        - wget
        - python3
      become: True

    - name: Get Kea DHCP Source
      git:
        repo: https://gitlab.isc.org/isc-projects/kea.git
        dest: ~/kea
        version: Kea-1.7.10

    - name: Install component dependencies
      shell:
        chdir: ~/kea
        cmd: "./hammer.py prepare-system -p local -w {{ item }}"
      loop:
        - mysql
        - pgsql
        - ccache
        - shell

    - name: Extract Premium hooks for Kea DHCP
      unarchive:
        remote_src: yes
        src: ~/kea-premium-1.7.10.tar
        dest: ~/kea/
