---
- hosts: all
  vars:
    vagrant:
      version: 2.2.19

  tasks:
    - name: Install base requirements
      ansible.builtin.package:
        name:
          - epel-release
          - git
          - vim
          - wget
          - python3
        state: present
      become: True

    - name: Install KVM Hypervisor
      ansible.builtin.package:
        name:
          - libvirt
          - qemu
          - qemu-kvm
          - virt-install
          - virt-top
          - libguestfs-tools
          - bridge-utils
        state: present
      become: True
      ignore_errors: yes

    - name: Enable and start libvirtd
      ansible.builtin.service:
        name: libvirtd
        enabled: yes
        state: started
      become: True

    - name: Add vagrant user to libvirt group
      ansible.builtin.user:
        name: "{{ item }}"
        append: yes
        groups: libvirt
      loop:
        - vagrant
      become: True

    - name: Install Vagrant Dependencies
      ansible.builtin.package:
        name:
          - make
          - rsync
          - gcc
          - zlib-devel
          - libvirt-devel
        state: present
      become: True
      ignore_errors: yes

    - name: Install Ruby
      ansible.builtin.package:
        name:
          - ruby
          - ruby-devel
        state: present
      become: True
      ignore_errors: yes

    - name: Download Vagrant RPM
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/vagrant/{{ vagrant.version }}/vagrant_{{ vagrant.version }}_x86_64.rpm"
        dest: /tmp/
      become: True

    - name: Install Vagrant
      ansible.builtin.dnf:
        name: "/tmp/vagrant_{{ vagrant.version }}_x86_64.rpm"
        state: present
      become: True
      ignore_errors: yes

    - name: Install vagrant-libvirt
      ansible.builtin.shell: CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt
